# Generated by Django 6.1 on 2026-09-26 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('media', 'Média partenaire'), ('institution', 'Institution'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depeche',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depeche',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.categorie'),
        ),
        migrations.AlterField(
            model_name='depeche',
            name='chapo',
            field=models.CharField(blank=True, help_text='Résumé rapide', max_length=500),
        ),
        migrations.AlterField(
            model_name='depeche',
            name='note_rejet',
            field=models.TextField(blank=True, help_text='Motif de rejet'),
        ),
        migrations.AlterField(
            model_name='diffusion',
            name='depeche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.depeche'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='depeche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.depeche'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='localisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='editorial.role'),
        ),
    ]
